name: build
on: [push]
jobs:
  build:
    name: build
    container: 
      image: golang:1.13
    runs-on: ubuntu-latest
    services:
      mysql:
        image: mysql:5.7
        env:
          MYSQL_ROOT_PASSWORD: password
        options: --health-cmd="mysqladmin ping" --health-interval=10s --health-timeout=5s --health-retries=5
    steps:
    - name: checkout
      uses: actions/checkout@v1
    - name: Build
      run: go build -v .
    - name: Test
      run: go test -race -coverprofile=coverage.txt -covermode=atomic
      env:
        TEST_DB_HOST: 'mysql'
    - uses: codecov/codecov-action@v1
      with:
        token: ${{ secrets.CODECOV_TOKEN }} #required
    - name: gobenchdata to gh-pages
      uses: bobheadxi/gobenchdata@v0.3.0
      with:
        PRUNE_COUNT: 30
        GO_TEST_FLAGS: -cpu 1,2
      env:
        TEST_DB_HOST: 'mysql'
        GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
