name: build
on: [push]
jobs:
  build:
    name: build
    container: 
      image: golang:1.13
    runs-on: ubuntu-latest
    services:
      mysql:
        image: mysql:5.7
        env:
          MYSQL_ROOT_PASSWORD: password
        options: --health-cmd="mysqladmin ping" --health-interval=10s --health-timeout=5s --health-retries=5
    steps:
    - name: checkout
      uses: actions/checkout@v1
    - name: Build
      run: go build -v .
    - name: Test
      run: go test -race -coverprofile=coverage.txt -covermode=atomic
      env:
        TEST_DB_HOST: 'mysql'
    - uses: codecov/codecov-action@v1
      with:
        token: ${{ secrets.CODECOV_TOKEN }} #required
    - name: Run benchmark
      run: go test -bench=. | tee output.txt
      env:
        TEST_DB_HOST: 'mysql'
      # Download previous benchmark result from cache (if exists)
#     - name: Download previous benchmark data
#       uses: actions/cache@v1
#       with:
#         path: ./cache
#         key: ${{ runner.os }}-benchmark
    # Run `github-action-benchmark` action
    - name: Store benchmark result
      uses: rhysd/github-action-benchmark@v1
      with:
        # What benchmark tool the output.txt came from
        tool: 'go'
        # Where the output from the benchmark tool is stored
        output-file-path: output.txt
        # Where the previous data file is stored
#         external-data-json-path: ./cache/benchmark-data.json
        # Workflow will fail when an alert happens
        auto-push: true
          # Show alert with commit comment on detecting possible performance regression
        alert-threshold: '120%'
        comment-on-alert: true
        fail-on-alert: true
        alert-comment-cc-users: '@jwentworth'
